# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReportIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReportIt
  # Add the Firebase pod for Google Analytics
  pod 'FirebaseAnalytics'

  # Add the pods for Firebase products you want to use in your app
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'

  target 'ReportItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReportItUITests' do
    # Pods for testing
  end

end
